version: '3.7'

services:
  autentication_imobiliaria:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - MYSQL_URL=jdbc:mysql://mysqlserver/autentication_imobiliaria
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
      
  mysqlserver:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=imobiliaria
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=imobiliaria_users
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
