version: "2.2"

services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=imobiliaria
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=imobiliaria_users
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql